### ISSUE TITLE
Complete how you can contribute section

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/annotations#1]
The "how you can contribute" section of the [README](https://github.com/tdwg/bdq/blob/master/README.md) currently only has boilerplate text:

> Depending on where group interaction takes place (GitHub, mailing list), provide some guidance on how interested parties can follow group activities (e.g. watch this repository, join mailing list) and how they can contribute.

Please update this to how people can actually contribute. There is actually a "becoming involved" section in the [charter](http://www.tdwg.org/activities/annotations-test/) that might serve as inspiration:

> Becoming involved
> 
> The Annotations Group is open to all interested parties. You can add yourself to the mailing list. Full membership is available to individuals who intend to be materially active in the group by request to the Convener. We are currently seeking reference implementations of annotation mechanisms and case studies for the annotation of data in general.

**Comment by chicoreus** [comment]
Completed in 267f3407ee9c7ac20ca65645379450ccebcd4200
