### ISSUE TITLE
Decide to add summary and/or rationale to README

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/annotations#2]
The README currently has the "Motivation" from the [charter](http://www.tdwg.org/activities/annotations-test/), which I named "Rationale" as in the IG READMEs.

The charter does also have a "Summary". I think it might be a bit dense for this repository, but I leave it up to you if you want to add it:

> Summary
> 
> Biodiversity informatics datasets are seldom, if ever, finished. New assertions are continually being made about biodiversity data, which may change their interpretation or require update of resources based on them. With subsequent study, researchers may apply new determinations to specimens. The scope of taxonomic concepts and taxon names change over time, as do geopolitical boundaries and names. Biodiversity data are continually enriched, for example, by extractions to add molecular profiles or dissections to improve morphological knowledge. Each piece of data may be distributed and linked in ways in which an assertion concerning a part of one data set is highly relevant to data being used elsewhere. Images of a specimen may be held in one or more repositories that are different from where its physical specimen is housed and any of these repositories may be the sites for new assertions about the data that are relevant to records in more places than the sites where the assertions are collected. Assertions about scientific data can be viewed as annotations of those data, with associated motivations, actions, and decisions that document the history of proposed, accepted, and rejected changes to those data. The domain content of an annotation is likely to be well described by existing, proposed, or future standards in the domain (e.g. Darwin Core, SDD, TCS, MRTG), but the concern of the annotation is at a different level. For example, an annotation might carry a Darwin Core assertion about a new determination of a specimen, but also assert that the determination is based upon a set of characters observed in particular regions of interest in a set of images of that specimen as seen by the annotator in an image repository. These linkages amongst the who, where, why, what, and when of assertions about data are the particular concerns of annotations. Annotations span many scales from change tracking within an individual data set to transport and linking of assertions across heterogeneous distributed data.
> 
> The Annotations Interest Group will provide a forum for discussion about all aspects of annotations in biodiversity informatics, develop cross-linkages with other interest groups and standards, and generate Task Groups to develop specific standards and best practices related to the annotation of biodiversity data.

**Comment by chicoreus** [comment]
Completed in cf352f48e2a12f55936f732abebf86396cec269a 

Added the last paragraph of the summary of the charter rephrased as the leading paragraph of the readme.
